#!/bin/bash

CONF_FILE=$HOME/.config/BullK/orgasample.conf
SRC_DIR=$PWD
BIN_DIR=$HOME/.local/bin
DATA_DIR=$HOME/Documents/orgasample

mkdir -p $DATA_DIR $HOME/.config/BullK/

ln -sf $SRC_DIR/orgasample-alsa $BIN_DIR/
ln -sf $SRC_DIR/orgasample-jack-2o $BIN_DIR/
ln -sf $SRC_DIR/orgasample-stereo.pd $DATA_DIR/

echo "data_dir $DATA_DIR" > $CONF_FILE
