#!/bin/bash

pushd $HOME

CONF_FILE=.config/BullK/orgasample/config
BANKS_FILE=.banks
SAMPLES_FILE=.samples
BANK_CONF_EXT=conf

ls banks > $BANKS_FILE

while read BANK
do
	pushd banks/$BANK
	ls *.wav > $SAMPLES_FILE
	if [ ! -e $CONF_FILE ]
	then touch $CONF_FILE
	fi
	popd
done < $BANKS_FILE

puredata -alsamidi -jack -audiodev 0,2 orgasample-stereo.pd &

#~ vkeybd --addr $(aconnect -o | grep "Pure Data" | grep client | cut -d: -f1 | cut -d\  -f2):0 &

popd
