#!/bin/bash

LOCKFILE=/tmp/bullk.lock

if [ $(uname -n) = "raspberrypi" ]; then
	RPI=true
	PD_OPTIONS="-noadc -audiooutdev 1 -outchannels 2 -nort -nogui"
else
	RPI=false
	PD_OPTIONS="-audiodev 3,3"
fi


#if [ -e $LOCKFILE ]; then
	#echo "BullK syntest est déjà démarré"
#else

	CONF_FILE=$HOME/.config/BullK/orgasample.conf
	DATA_DIR=$(grep data_dir $CONF_FILE | cut -d\  -f2)
	#echo $DATA_DIR
	BANKS_FILE=.banks
	SAMPLES_FILE=.samples
	BANK_CONF_EXT=conf

	if [ ! -d $DATA_DIR ]
	then
		mkdir -p $DATA_DIR/banks/0
	fi
	
	pushd $DATA_DIR

	ls banks > $BANKS_FILE

	while read BANK
	do
		pushd banks/$BANK
		ls *.wav > $SAMPLES_FILE
		if [ ! -e .$BANK.$BANK_CONF_EXT ]
		then touch .$BANK.$BANK_CONF_EXT
		fi
		popd
	done < $BANKS_FILE

	pd -alsamidi -alsa $PD_OPTIONS orgasample-stereo.pd &
	sleep 1

	if ($RPI)
	then
		if [ -z $(pidof vkeybd) ]
		then vkeybd --addr $(aconnect -o | grep "Pure Data" | grep client | cut -d: -f1 | cut -d\  -f2):0 &
		fi
	fi

	KBPORT=$(aconnect -i | grep Oxygen | grep client | cut -d: -f1 | cut -d\  -f2):0
	PDPORT=$(aconnect -o | grep "Pure Data" | grep client | cut -d: -f1 | cut -d\  -f2):0
	aconnect $KBPORT $PDPORT
	
	until [ -z "$(ps -a | grep puredata)" ]; do
		sleep 1
	done

	popd

#fi
#sleep 10000


